status = error
name = SparkQuiet

rootLogger.level = error
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n